version: '3.8'

services:
  # MediaPipe TouchDesigner Bridge Service
  mediapipe-bridge:
    build:
      context: .
      dockerfile: Dockerfile.bridge
    container_name: mediapipe_touchdesigner_bridge
    ports:
      - "7000:7000"  # OSC port for TouchDesigner communication
    volumes:
      - ./backend:/app/backend
      - ./models:/app/models
      - ./data:/app/data
      - ./config:/app/config
      - .:/app/scripts
    environment:
      - PYTHONPATH=/app
      - DISPLAY=${DISPLAY:-:0.0}  # For camera access on Linux
    devices:
      - /dev/video0:/dev/video0  # Camera access (comment out on Windows)
    network_mode: "host"  # Required for OSC communication to TouchDesigner
    restart: unless-stopped
    command: python enhanced_mediapipe_touchdesigner_bridge.py

  # Alternative: Standard bridge without enhancements
  standard-bridge:
    build:
      context: .
      dockerfile: Dockerfile.bridge
    container_name: standard_mediapipe_bridge
    ports:
      - "7001:7000"  # Alternative OSC port
    volumes:
      - ./backend:/app/backend
      - ./models:/app/models
      - ./data:/app/data
      - ./config:/app/config
    environment:
      - PYTHONPATH=/app
    devices:
      - /dev/video0:/dev/video0  # Camera access (comment out on Windows)
    network_mode: "host"
    profiles: ["standard"]  # Only run when explicitly requested
    command: python mediapipe_touchdesigner_bridge.py

volumes:
  models_data: