# Model Architecture Configuration
model:
  type: "CNN"
  input_size: [224, 224, 3]
  num_classes: 5  # dog, bird, rabbit, butterfly, snake
  architecture:
    - conv2d: {filters: 32, kernel_size: 3, activation: "relu"}
    - maxpool2d: {pool_size: 2}
    - conv2d: {filters: 64, kernel_size: 3, activation: "relu"}
    - maxpool2d: {pool_size: 2}
    - conv2d: {filters: 128, kernel_size: 3, activation: "relu"}
    - maxpool2d: {pool_size: 2}
    - dropout: {rate: 0.25}
    - flatten: {}
    - dense: {units: 512, activation: "relu"}
    - dropout: {rate: 0.5}
    - dense: {units: 5, activation: "softmax"}

# Training Configuration
training:
  batch_size: 32
  epochs: 50
  learning_rate: 0.001
  optimizer: "Adam"
  loss_function: "categorical_crossentropy"
  metrics: ["accuracy"]
  validation_split: 0.2
  early_stopping:
    patience: 5
    monitor: "val_accuracy"
    min_delta: 0.001

# Data Preprocessing
preprocessing:
  resize: [224, 224]
  normalize: true
  augmentation:
    rotation_range: 20
    width_shift_range: 0.2
    height_shift_range: 0.2
    horizontal_flip: true
    brightness_range: [0.8, 1.2]
    zoom_range: 0.2

# Inference Configuration
inference:
  confidence_threshold: 0.8
  batch_size: 1
  preprocessing_pipeline:
    - resize: [224, 224]
    - normalize: true
    - tensor_conversion: true